# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="af-magic"

setopt HIST_IGNORE_ALL_DUPS


# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git git postgres python virtualenv django)

source $ZSH/oh-my-zsh.sh

#nerdtree fix
export LC_ALL=en_US.utf-8 
export LANG="$LC_ALL" 

# named folders
export SALT=/srv/salt
export SITE_PACKAGES={{ pillar['directories']['env'] }}/lib/python2.7/site-packages
export {{ pillar['main_user']|upper }}={{ pillar['directories']['src'] }}
export CSS={{ pillar['directories']['src'] }}/static/css
export JS={{ pillar['directories']['src'] }}/static/js

# Aliases
alias activate-virtualenv=". {{ pillar['directories']['env'] }}/bin/activate"
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"

# Customize to your needs...
export PATH=$PATH:/usr/bin
export PATH=$PATH:/bin
export PATH=$PATH:/usr/sbin
export PATH=$PATH:/sbin
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/usr/X11/bin
