from rest_framework import serializers

class ItemSerializer(serializers.Serializer):
        etiqueta = serializers.CharField()
        sku = serializers.CharField()
	surtido_id = serializers.IntegerField()
        proveedor = serializers.CharField(required=False)
	variation_id = serializers.IntegerField()
        marca = serializers.CharField()
        color_original = serializers.CharField(required=False)
        linea = serializers.CharField(required=False)
        talla = serializers.CharField()
        color = serializers.CharField(required=False)
	cost = serializers.IntegerField()
	ingresed_by = serializers.IntegerField()
	ingresed = serializers.DateTimeField()
	current_location = serializers.IntegerField(required=False)
	location_list = serializers.CharField(required=False)
	sold_by = serializers.IntegerField(required=False)
	sold_to = serializers.IntegerField(required=False)
	agent_id = serializers.IntegerField(required=False)
	sold = serializers.DateTimeField(required=False)
	price = serializers.IntegerField(required=False)
	status = serializers.IntegerField(required=False)
